export const SET_ALL_TICKETS = 'AVIA.SET_ALL_TICKETS';
export const GET_SEARCH_ID = 'AVIA.GET_SEARCH_ID';
export const SET_STOP_REQUEST = 'AVIA.SET_STOP_REQUEST';
export const SET_FILTERED_TICKETS = 'AVIA.SET_FILTERED_TICKETS';
export const SET_FILTER_FOR_TICKETS = 'AVIA.SET_FILTER_FOR_TICKETS';
